### ISSUE TITLE
Files uploaded with `tacl --data /path/to/file.ext` have the specified path prepended to name on destination

### ISSUE THREAD

**Issue by wherewillowsare** [unioslo/tsd-api-client#1]
Running e.g. `tacl --data /path/to/file.ext` results in the uploaded file in destination folder with the name `_path_to_file.ext`, e.g. both the specified path and the name of the file form the name of uploaded file, with slashes replaced with underscore.

Expected behavior is to have the uploaded file have the same name as the file specified for uploading with `tacl --data`.

**Comment by leondutoit** [comment]
I have tested this and I think it is solved. @wherewillowsare feel free to confirm :)
