### ISSUE TITLE
The list of guides in TACL's README file is obsolete

### ISSUE THREAD

**Issue by ofrei** [unioslo/tsd-api-client#128]
Currently the getting started section of https://github.com/unioslo/tsd-api-client/blob/master/README.md is somewhat obsolete, showing this information:
```
tacl --guide config
tacl --guide uploads
tacl --guide downloads
tacl --guide sync
tacl --guide topics # to see all guides available
tacl --help
```

A correct list as of today would be like this:
```
tacl --guide topics  # to see all guides available
tacl --help          # overview of all options

tacl --guide config
tacl --guide uploads
tacl --guide downloads
tacl --guide automation
tacl --guide debugging
tacl --guide sync
```

NB! ``tacl --guide topics`` currently does not list ``tacl --guide sync``, but I checked that it's still available. Great if both README and ``tacl --guide topics`` output is updated. Or, alternatively, all guides could be moved to the README file in this repository - I think this way it would be easier for new users to get started, as they don't need to install the tool, but can go through all guides directly on github.

**Comment by leondutoit** [comment]
I've removed the list from the README.
