### ISSUE TITLE
v1.8.3: persistent token bug

### ISSUE THREAD

**Issue by kasbohm** [unioslo/tsd-api-client#13]
Hi! 
The ```--print-token-for ``` argument returns a persistent token in v1.4.0. The same command in v1.8.3 returns token:None. I have not tested with intermittent versions.

``` 
tsd-s3cmd --print-token-for
User > p23-ingeam
Password > xxx
OTP > xxx
To use this token without using tsd-s3cmd execute your command as follows:
s3cmd --add-header=token:None --add-header=x-project-select:p23 COMMAND
```

**Comment by leondutoit** [comment]
Thanks for the report, I'll look into it soon.

**Comment by leondutoit** [comment]
Actually, I think you've omitted something from your command, it should be `tsd-s3cmd --print-token-for put`. Then it works.

**Comment by kasbohm** [comment]
Thanks, it now somehow works both with and without ``` put ``` for both versions after some installing and uninstalling. User error!
