### ISSUE TITLE
File transfer shouldn't require write permission on file

### ISSUE THREAD

**Issue by monoburn** [unioslo/tsd-api-client#15]
fileapi.py opens the file to import using open(filename,'rb+'). Should be changed to 'rb' to allow transferring files that are read-only on the client side.

This concerns the latest version 1.8.3.
![Skjermbilde 2019-07-01 11 20 29](https://user-images.githubusercontent.com/79774/60428809-00db1d80-9bfa-11e9-84bd-199584ce9bea.png)

**Comment by monoburn** [comment]
![Skjermbilde 2019-07-01 11 20 29](https://user-images.githubusercontent.com/79774/60428782-f28d0180-9bf9-11e9-8956-f3eeddd12860.png)

**Comment by leondutoit** [comment]
Thanks will change.

**Comment by monoburn** [comment]
Has this issue been fixed with the latest v2 release?
