### ISSUE TITLE
how to use tacl to upload files to import link

### ISSUE THREAD

**Issue by marrip** [unioslo/tsd-api-client#156]
I got an import link from a collaborator and it is basically only the link with a hash in the end and a password. I can log on and upload data via the browser but is it possible to upload data via tacl as well? And if yes, how do I do it?

**Comment by kouylekov-usit** [comment]
Hei, 

tacl now supports import links as of version 3.6.1. N.B. If the import link cantinas an import path, the path must exist. 

Best Milen

**Comment by marrip** [comment]
amazing, thank you. Just one question how do I specify the link and the password. I tried:

```bash
tacl p11 --upload file.txt --remote-path https://remote.path/some-hash
```

but it didn't ask me for any password but prints:

```bash
your session has expired, please authenticate
client not registered
```

I checked the `guide` but didn't figure out how to correctly supply the link and password.
