### ISSUE TITLE
Authentication error after a --register

### ISSUE THREAD

**Issue by monoburn** [unioslo/tsd-api-client#16]
The python client for the TSD file import/export API don’t reuse the credentials defined using ’tacl —register’. See screenshot.
![tsd-api-client-auth-err](https://user-images.githubusercontent.com/79774/60430260-2a497880-9bfd-11e9-9733-fe85cb03177d.png)
It works when I don’t include the ‘—pnum’ option and is prompted for username/password/OTP.

I run this from a server connected to the UiO network with IP 129.240.215.254

**Comment by leondutoit** [comment]
When you include `--pnum p22` you are attempting to perform upload with _basic_ authentication. This is designed to fail unless your host IP has been whitelisted to allow it. In this case, your host IP has not been allowed to perform basic auth, so this is not a bug, but the intended behaviour. If you wish to register you host IP for basic auth upload, please send a support case to TSD at tsd-drift@usit.uio.no. This is also documented in `tacl --data-guide`.
