### ISSUE TITLE
Unable to access tacl documentation online

### ISSUE THREAD

**Issue by ofrei** [unioslo/tsd-api-client#19]
``tacl --data-guide`` says
```
   API docs
        ~~~~~~~~
        test.api.tsd.usit.no/v1/docs/tsd-api-integration.html
```
However I can't access http://test.api.tsd.usit.no/v1/docs/tsd-api-integration.html

**Comment by leondutoit** [comment]
Noted. This is not a bug in the client code, so please send this info in the support case we have going at TSD :) .
