### ISSUE TITLE
tsd-s3cmd asks credentials before it validates parameters

### ISSUE THREAD

**Issue by ofrei** [unioslo/tsd-api-client#2]
Hi @leondutoit 

I've noticed that tsd-s3cmd asks for password & OTP very early, and then it may fail with some really stupid error that in principle could be discovered without asking for credentials.  Some other commands don't ask for credentials (like ``tsd-s3cmd --help``). Would it be possible to do more validation before checking credentials?

```
(python2) [oleksanf@tos-spw08 test_s3]$ tsd-s3cmd put . s3://ofreibucket
User > pNN-XXXX
Password >
OTP > NNNNNN
ERROR: Parameter problem: Use --recursive to upload a directory: .
```

Feel free to close this unless it is a quick fix...

**Comment by leondutoit** [comment]
Hi @ofrei, thanks for reporting :) I'll have a look at whether this is possible with a reasonable amount of effort, and let you know.

**Comment by leondutoit** [comment]
Unfortunately this is something we have to live with.
