### ISSUE TITLE
installation failed on MacOS

### ISSUE THREAD

**Issue by nanjiangshu** [unioslo/tsd-api-client#21]
Hi,

It seems the installation does not work on MacOS (Mojave) using anaconda. 

I got this error when running `tacl --help`

```
Traceback (most recent call last):
  File "/Users/nanjiang/anaconda3/envs/py27/bin/tacl_data", line 4, in <module>
    __import__('pkg_resources').run_script('tsd-api-client==1.8.3', 'tacl_data')
  File "/Users/nanjiang/anaconda3/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py",   line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/nanjiang/anaconda3/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py",   line 1437, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/tacl_data' not found in metadata at '/data3/work/BILS/ project/D2D3/tsd-api-client/tsd_api_client.egg-info'
```

Guess the problem is with the setup.py.

Best,

Nanjiang

**Comment by leondutoit** [comment]
You're welcome to submit a pull request which fixes this :)

**Comment by sigven** [comment]
I get the same error, but I am afraid I cant't see what is wrong with `setup.py`.

**Comment by leondutoit** [comment]
If you are not able to fix it, then please provide a way for me to try and reproduce it: pointer to installing anaconda on mac, and how you install it.

**Comment by nanjiangshu** [comment]
Hi @leondutoit, I figured out the problem. The error occurs only when running the command ```tacl --help``` inside the source code folder. The problem is that after running 
``` python setup.py install```
a local egg-info will be created inside the source code folder. When running ```tacl --help``` within this folder, python tries to use this egg-info instead of the one installed. 

The command runs normally outside of this folder.

Best,

Nanjiang

**Comment by sigven** [comment]
Thanks for our help, @nanjiangshu!

**Comment by leondutoit** [comment]
Right, I'll update the readme to recommend using `pip install https://github.com/unioslo/tsd-api-client/archive/v2.0.0.tar.gz`, e.g. for installing the client, so this problem is less likely to occus.
