### ISSUE TITLE
tsd-s3cmd rb not supported

### ISSUE THREAD

**Issue by kjellp** [unioslo/tsd-api-client#25]
We have a use case were we may want to create a number of buckets for different uploads, before moving the data forward to internal project file systems. Removing these buckets after some time is currently not possible.

**Comment by leondutoit** [comment]
Hi Kjell, can we please discuss this on email in the TSD contact RT? It is not really a bug in the client, and will require a meeting with IT sec, since as you note, it is beyond what the initial use case was about.

**Comment by kjellp** [comment]
Hi Leon, the use case I'm now referring to is NorSeq data uploads (not the local EGA). Not sure what you refer to as the inital use case. But no problem, I see clearifications would be needed before actual implementation can change in the repo.

**Comment by leondutoit** [comment]
The initial Norseq case was only about importing data from SAFE to TSD, and didn't even involve the s3 API. Way back when we discussed setting up the s3 API IT Sec approved a small set of operations so we can start conservative, and stay consistent with the general model for import and exports. Hope that suffices as an explanation. Chat more on email then.
