### ISSUE TITLE
More meaningful error message upon wrong username, password, otp combination.

### ISSUE THREAD

**Issue by kjellp** [unioslo/tsd-api-client#26]
Currently this is returned:
- xml parsing error 
- a html section containing "Authorization required" 
- S3 error: 401 (Unauthorized)

And this is the exact same output that will be returned if a non-supported method like "ls" is executed **with valid** username, password, otp combination....

**Comment by leondutoit** [comment]
It is a security measure not to give out such information, because then attackers cannot learn more about the API or a user's credentials, by systematically abusing it. Unfortunately, that compromises user experience.
