### ISSUE TITLE
 If  --download-id is supposed to work for both –import and –export, mention that in the –help text. If not there is a bug

### ISSUE THREAD

**Issue by leigh-uio** [unioslo/tsd-api-client#39]

**Comment by haatveit** [comment]
There's an `--upload-id` parameter for resuming imports, while `--download-id` is supposed to be for resuming exports. 

Perhaps it would make sense if both could be unified to `--id` or `--file-id` in the tacl script?

Is this what you were referring to?

**Comment by leigh-uio** [comment]
I can't find the original support ticket where the user mentioned this, so I'm not certain, but what you say sounds correct.
