### ISSUE TITLE
Create container for running the package

### ISSUE THREAD

**Issue by haatveit** [unioslo/tsd-api-client#81]
Should be quite straightforward to prepare this, perhaps publishing to [GitHub Packages](https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages) as well.

It would be nice to use [distroless](https://github.com/GoogleContainerTools/distroless) base images but the Python 3 one is apparently still marked as experimental.

**Comment by leondutoit** [comment]
When does one need to run this in a container? (Not that I'm against it).

**Comment by haatveit** [comment]
> When does one need to run this in a container? (Not that I'm against it).
When it's less hassle than not doing so, I'd argue.

Python software is very portable, but the packaging is and has always been a
mess.  I've had pip installed packages "disappear" (because the
`$PREFIX/lib/python3.x` path is version specific) and virtual environments
break a few times too many for my taste.

On macOS when using Homebrew it always tracks the latest Python release (at
least by default, likely you can pin it somehow). Fedora's yearly releases also
bump the system Python 3. Without using something like pyenv or a stable OS
like RHEL, the system Python is basically a moving target and stuff will break.

I like using containers for software not managed by the OS because it's hassle
free - they just work.

**Comment by leondutoit** [comment]
Fair enough, just wondered if there was a specific use case.
